---
# Changes here will be overwritten by Copier
_commit: v2.0.0-rc2-37-g12fce82
_src_path: gh:remerge/template
is_golang_library: true
project_id: go-server
project_license: private
project_name: Go Server Framework
project_owner: core
project_type: default
use_ansible: false
use_golang: true
use_nomad: false
use_python: false
use_terraform: false
