---
name: go-update-deps

on:
  push:
    branches: [main, master]

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  check-for-internal-dependency-updates:
    uses: remerge/workflows/.github/workflows/check-repos-i-depend-on.yml@main
    with:
      assign_to: ${{ github.actor }}
    secrets:
      app_id: ${{ secrets.DEPUPDATER_APP_ID }}
      app_key: ${{ secrets.DEPUPDATER_APP_KEY }}
      ssh_key: ${{ secrets.DEPLOY_USER_SSH_KEY }}
  notify-internal-dependants:
    uses: remerge/workflows/.github/workflows/notify-repos-that-depend-on-me.yml@main
    with:
      assign_to: ${{ github.actor }}
    secrets:
      app_id: ${{ secrets.DEPUPDATER_APP_ID }}
      app_key: ${{ secrets.DEPUPDATER_APP_KEY }}
